# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dist_from_point": "00_gram.ipynb",
         "lines_to_layer": "00_gram.ipynb",
         "layer_to_lines": "00_gram.ipynb",
         "ChordArray": "00_gram.ipynb"}

modules = ["gram.py"]

doc_url = "https://anaka.github.io/good_robot/"

git_url = "https://github.com/anaka/good_robot/tree/master/"

def custom_doc_links(name): return None
