# AUTOGENERATED! DO NOT EDIT! File to edit: 03_quiver.ipynb (unless otherwise specified).

__all__ = ['linebreak']

# Cell
import bezier
from matplotlib.collections import LineCollection
from matplotlib import pyplot as plt
import numpy as np
from penkit import write, preview
from pathlib import Path
import seaborn as sns
from tqdm import tqdm

import good_robot.gram as gg
linebreak = np.array([[np.nan],[np.nan]])
